all:
	tiled_code_gen -f RGB565_Swap --pdf --geste level_0.tmx level_1.tmx \
        level_2.tmx level_3.tmx level_4.tmx level_5.tmx level_6.tmx \
	level_7.tmx level_8.tmx title_screen.tmx Misc_Objects.tmx \
	-o ../src/assets -d ../docs/
