with GESTE;
pragma Style_Checks (Off);
package Game_Assets.Tileset_Collisions is

   Tiles : aliased constant GESTE.Tile_Collisions_Array :=
     (
      1 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      2 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      3 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      4 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      5 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      6 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      7 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      8 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      9 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      10 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      11 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      12 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      13 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      14 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      15 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      16 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      17 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      18 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      19 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      20 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      21 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      22 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      23 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      24 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      25 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      26 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      27 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      28 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      29 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      30 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      31 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      32 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      33 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      34 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      35 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      36 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      37 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      38 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      39 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      40 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      41 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      42 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      43 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      44 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      45 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      46 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      47 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      48 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      49 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      50 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      51 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      52 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      53 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      54 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      55 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      56 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      57 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      58 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      59 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      60 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      61 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      62 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      63 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      64 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      65 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      66 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      67 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      68 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      69 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      70 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      71 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      72 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      73 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      74 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      75 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      76 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      77 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      78 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      79 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      80 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      81 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      82 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      83 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      84 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      85 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      86 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      87 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      88 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      89 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      90 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      91 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      92 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      93 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      94 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      95 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      96 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      97 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      98 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      99 => ((True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True),
             (True,True,True,True,True,True,True,True)),
      100 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      101 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      102 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      103 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      104 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      105 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      106 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      107 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      108 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      109 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      110 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      111 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      112 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      113 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      114 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      115 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      116 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      117 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      118 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      119 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      120 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      121 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      122 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      123 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      124 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      125 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      126 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      127 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      128 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      129 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      130 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      131 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      132 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      133 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      134 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      135 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      136 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      137 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      138 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      139 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      140 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      141 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      142 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      143 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      144 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      145 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      146 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      147 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      148 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      149 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      150 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      151 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      152 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      153 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      154 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      155 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      156 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      157 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      158 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      159 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      160 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      161 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      162 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      163 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      164 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      165 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      166 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      167 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      168 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      169 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      170 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      171 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      172 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      173 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      174 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      175 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      176 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      177 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      178 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      179 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      180 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      181 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      182 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      183 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      184 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      185 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      186 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      187 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      188 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      189 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      190 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      191 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      192 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      193 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)),
      194 => ((False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False),
             (False,False,False,False,False,False,False,False)));
end Game_Assets.Tileset_Collisions;
